"""Static package exports for editor tooling."""

# This file is auto-generated by scripts/generate_init_pyi.py.
# Do not edit it manually; re-run the generator after changing public exports.

from .age_structured_population import AgeStructuredPopulation

from .discrete_generation_population import DiscreteGenerationPopulation

from .gamete_allele_conversion import (
    GameteAlleleConversionRule,
    GameteHaploidGenomeConversionRule,
    GameteConversionRuleSet,
)

from .genetic_entities import (
    Gene,
    Allele,
    Haplotype,
    HaploidGenome,
    HaploidGenotype,
    Genotype,
    Genome,
    DiploidGenotype,
    DiploidGenome,
)

from .genetic_patterns import GenotypePatternParser

from .genetic_structures import (
    Locus,
    Chromosome,
    Linkage,
    Species,
    GenomeTemplate,
    Karyotype,
)

from .hook_dsl import (
    OpType,
    HookOp,
    Op,
    CompiledHookPlan,
    CompiledHookDescriptor,
    HookProgram,
    HookExecutor,
    execute_csr_event_arrays,
    execute_csr_event_program,
    build_hook_program,
    noop_hook,
    compile_combined_hook,
    CompiledEventHooks,
    hook,
    compile_declarative_hook,
    compile_selector_hook,
    COND_ALWAYS,
    COND_TICK_EQ,
    COND_TICK_MOD,
    COND_TICK_GE,
    COND_TICK_GT,
    COND_TICK_LE,
    COND_TICK_LT,
    EVENT_FIRST,
    EVENT_EARLY,
    EVENT_LATE,
    EVENT_FINISH,
    RESULT_CONTINUE,
    RESULT_STOP,
)

from .numba_compat import binomial_2d, multinomial_rows, multinomial

from .numba_utils import (
    NUMBA_ENABLED,
    is_numba_enabled,
    enable_numba,
    disable_numba,
    jitclass_switch,
    njit_switch,
    numba_disabled,
    numba_enabled,
    with_numba_disabled,
    with_numba_enabled,
)

from .population_builder import (
    AgeStructuredPopulationBuilder,
    DiscreteGenerationPopulationBuilder,
)

from .population_config import (
    NO_COMPETITION,
    FIXED,
    LOGISTIC,
    LINEAR,
    CONCAVE,
    BEVERTON_HOLT,
    extract_gamete_frequencies,
    extract_gamete_frequencies_by_glab,
    extract_zygote_frequencies,
)

from .recipes import HomingDrive

from .type_def import Sex, Age, GameteLabel

from .zygote_allele_conversion import (
    ZygoteAlleleConversionRule,
    ZygoteGenotypeConversionRule,
    ZygoteConversionRuleSet,
)

__all__ = [
    "Age",
    "AgeStructuredPopulation",
    "AgeStructuredPopulationBuilder",
    "Allele",
    "BEVERTON_HOLT",
    "CONCAVE",
    "COND_ALWAYS",
    "COND_TICK_EQ",
    "COND_TICK_GE",
    "COND_TICK_GT",
    "COND_TICK_LE",
    "COND_TICK_LT",
    "COND_TICK_MOD",
    "Chromosome",
    "CompiledEventHooks",
    "CompiledHookDescriptor",
    "CompiledHookPlan",
    "DiploidGenome",
    "DiploidGenotype",
    "DiscreteGenerationPopulation",
    "DiscreteGenerationPopulationBuilder",
    "EVENT_EARLY",
    "EVENT_FINISH",
    "EVENT_FIRST",
    "EVENT_LATE",
    "FIXED",
    "GameteAlleleConversionRule",
    "GameteConversionRuleSet",
    "GameteHaploidGenomeConversionRule",
    "GameteLabel",
    "Gene",
    "Genome",
    "GenomeTemplate",
    "Genotype",
    "GenotypePatternParser",
    "HaploidGenome",
    "HaploidGenotype",
    "Haplotype",
    "HomingDrive",
    "HookExecutor",
    "HookOp",
    "HookProgram",
    "Karyotype",
    "LINEAR",
    "LOGISTIC",
    "Linkage",
    "Locus",
    "NO_COMPETITION",
    "NUMBA_ENABLED",
    "Op",
    "OpType",
    "RESULT_CONTINUE",
    "RESULT_STOP",
    "Sex",
    "Species",
    "ZygoteAlleleConversionRule",
    "ZygoteConversionRuleSet",
    "ZygoteGenotypeConversionRule",
    "binomial_2d",
    "build_hook_program",
    "compile_combined_hook",
    "compile_declarative_hook",
    "compile_selector_hook",
    "disable_numba",
    "enable_numba",
    "execute_csr_event_arrays",
    "execute_csr_event_program",
    "extract_gamete_frequencies",
    "extract_gamete_frequencies_by_glab",
    "extract_zygote_frequencies",
    "hook",
    "is_numba_enabled",
    "jitclass_switch",
    "multinomial",
    "multinomial_rows",
    "njit_switch",
    "noop_hook",
    "numba_disabled",
    "numba_enabled",
    "with_numba_disabled",
    "with_numba_enabled",
]
