"""Type stub for the optional native Rust extension ``natal._engine_rs``."""

from collections.abc import Callable

import numpy as np
from numpy.typing import NDArray

def equilibrium_metrics(
    blueprint: object,
    params: object,
) -> tuple[float, float]:
    """Compute (expected_competition_strength, expected_survival_rate) from contracts."""


class EngineSession:
    def trigger_event(self, event: int, deme_id: int = 0) -> int: ...
    def observe_current(self, mask: NDArray[np.float64], selected: list[int], collapse_age: bool, aggregate: bool) -> tuple[int, NDArray[np.float64]]: ...
    def execution_state(self) -> tuple[str, int]: ...
    def stop(self) -> None: ...
    def bind_history(self, history: HistoryStore) -> None: ...
    def record_history(self, continuation: bool) -> None: ...
    """Rust-owned contract pair, RNG, and CSR hook program."""

    def __init__(self, blueprint: object, params: object, seed: int = 0) -> None: ...
    def refresh_params(self, fields: list[str], source: object) -> None: ...
    def apply(self, writes: dict[str, float]) -> None: ...
    def get_scalar(self, name: str) -> float: ...
    def get_tensor(self, name: str) -> NDArray[np.float64]: ...
    def tensor_write(self, field: str, values: NDArray[np.float64]) -> None: ...
    def set_custom_slots(self, values: object) -> None: ...
    def get_custom_slots(self) -> dict[str, bool | int | float | NDArray[np.float64]]: ...
    def set_execution_flags(self, stochastic: bool, continuous_sampling: bool, fixed_egg_count: bool, extreme_speed_mode: int) -> None: ...
    def set_hook_program(self, program: object) -> None: ...
    def clear_hook_program(self) -> None: ...
    def set_python_callbacks(
        self,
        first: list[Callable[..., int]],
        early: list[Callable[..., int]],
        late: list[Callable[..., int]],
        finish: list[Callable[..., int]] | None = None,
    ) -> None: ...
    def clear_python_callbacks(self) -> None: ...
    def reseed(self, seed: int) -> None: ...
    def drain_eco_journal(self) -> list[tuple[int, int, float, float]]: ...
    def reproduction(
        self,
        individual_count: NDArray[np.float64],
        sperm_storage: NDArray[np.float64],
    ) -> None: ...
    def survival(
        self,
        individual_count: NDArray[np.float64],
        sperm_storage: NDArray[np.float64],
    ) -> None: ...
    def aging(
        self,
        individual_count: NDArray[np.float64],
        sperm_storage: NDArray[np.float64],
    ) -> None: ...
    def tick(self, deme_id: int) -> int: ...
    def set_state(
        self, ind_flat: NDArray[np.float64], sperm_flat: NDArray[np.float64], tick: int
    ) -> None: ...
    def state_snapshot(
        self,
    ) -> tuple[int, NDArray[np.float64], NDArray[np.float64]]: ...
    def counts(self) -> tuple[float, float, float]: ...
    def run(
        self,
        n_ticks: int,
        record_interval: int,
        observation_mask: NDArray[np.float64] | None = None,
        checkpoint_every: int = 0,
    ) -> tuple[int, NDArray[np.float64], bool]: ...
    def snapshot_state(
        self,
    ) -> tuple[int, NDArray[np.float64], NDArray[np.float64], list[int], dict[str, object]]: ...
    def restore_state(
        self,
        tick: int,
        ind_flat: NDArray[np.float64],
        sperm_flat: NDArray[np.float64],
        rng_words: list[int],
        ecology: dict[str, object],
    ) -> int: ...
    def restore_from_checkpoint(
        self,
        tick: int,
    ) -> tuple[int, dict[str, object]] | None: ...
    def clear_checkpoints(self) -> None: ...
    def retain_checkpoints_from(self, from_tick: int) -> None: ...
    def truncate_checkpoints(self, retain_until_tick: int) -> None: ...


class DiscreteEngineSession:
    def trigger_event(self, event: int, deme_id: int = 0) -> int: ...
    def observe_current(self, mask: NDArray[np.float64], selected: list[int], collapse_age: bool, aggregate: bool) -> tuple[int, NDArray[np.float64]]: ...
    def execution_state(self) -> tuple[str, int]: ...
    def stop(self) -> None: ...
    def bind_history(self, history: HistoryStore) -> None: ...
    def record_history(self, continuation: bool) -> None: ...
    """Rust-owned discrete-generation contract pair, RNG, and CSR hooks."""

    def __init__(self, blueprint: object, params: object, seed: int = 0) -> None: ...
    def refresh_params(self, fields: list[str], source: object) -> None: ...
    def apply(self, writes: dict[str, float]) -> None: ...
    def get_scalar(self, name: str) -> float: ...
    def get_tensor(self, name: str) -> NDArray[np.float64]: ...
    def tensor_write(self, field: str, values: NDArray[np.float64]) -> None: ...
    def set_custom_slots(self, values: object) -> None: ...
    def get_custom_slots(self) -> dict[str, bool | int | float | NDArray[np.float64]]: ...
    def set_execution_flags(self, stochastic: bool, continuous_sampling: bool, fixed_egg_count: bool, extreme_speed_mode: int) -> None: ...
    def set_hook_program(self, program: object) -> None: ...
    def clear_hook_program(self) -> None: ...
    def set_python_callbacks(
        self,
        first: list[Callable[..., int]],
        early: list[Callable[..., int]],
        late: list[Callable[..., int]],
        finish: list[Callable[..., int]] | None = None,
    ) -> None: ...
    def clear_python_callbacks(self) -> None: ...
    def reseed(self, seed: int) -> None: ...
    def drain_eco_journal(self) -> list[tuple[int, int, float, float]]: ...
    def tick(self, wf: bool) -> int: ...
    def set_state(self, ind_flat: NDArray[np.float64], tick: int) -> None: ...
    def state_snapshot(self) -> tuple[int, NDArray[np.float64]]: ...
    def counts(self) -> tuple[float, float, float]: ...
    def run(
        self,
        n_ticks: int,
        record_interval: int,
        wf: bool,
        observation_mask: NDArray[np.float64] | None = None,
        checkpoint_every: int = 0,
    ) -> tuple[int, NDArray[np.float64], bool]: ...
    def snapshot_state(
        self,
    ) -> tuple[int, NDArray[np.float64], list[int], dict[str, object]]: ...
    def restore_state(
        self,
        tick: int,
        ind_flat: NDArray[np.float64],
        rng_words: list[int],
        ecology: dict[str, object],
    ) -> int: ...
    def restore_from_checkpoint(
        self,
        tick: int,
    ) -> tuple[int, dict[str, object]] | None: ...
    def clear_checkpoints(self) -> None: ...
    def retain_checkpoints_from(self, from_tick: int) -> None: ...
    def truncate_checkpoints(self, retain_until_tick: int) -> None: ...


class HeterogeneousSpatialEngineSession:
    def refresh_deme_parameters(self, deme: int, fields: list[str], source: object) -> None: ...
    def set_deme_custom_slots(self, deme: int, source: object) -> None: ...
    def trigger_deme_event(self, deme: int, event: int) -> int: ...
    def get_deme_scalar(self, deme: int, name: str) -> float: ...
    def get_deme_tensor(self, deme: int, name: str) -> NDArray[np.float64]: ...
    def get_deme_custom_slots(self, deme: int) -> dict[str, bool | int | float | NDArray[np.float64]]: ...
    def apply_deme(self, deme: int, writes: dict[str, float]) -> None: ...
    def tensor_write_deme(self, deme: int, field: str, values: NDArray[np.float64]) -> None: ...
    def observe_current(self, mask: NDArray[np.float64], selected: list[int], collapse_age: bool, aggregate: bool) -> tuple[int, NDArray[np.float64]]: ...
    def execution_state(self) -> tuple[str, int]: ...
    def stop(self) -> None: ...
    def run_steps(self, n_ticks: int, record_interval: int) -> tuple[int, bool]: ...
    def bind_history(self, history: HistoryStore) -> None: ...
    def record_history(self, continuation: bool) -> None: ...
    """Rust-owned heterogeneous spatial session over the variant bank.

    One shared blueprint, one columnized ecology set (per-deme ``Params``
    columns), a bank of shared genetics variants, and a per-deme variant
    index — no per-deme contract clones.  The session also owns the
    stacked counts, sperm storage, tick, and one persistent RNG stream
    per deme (``seed ^ deme``, advancing across ticks); ``run_tick``
    carries control parameters only and runs lifecycle then migration
    inside Rust.
    """

    def __init__(
        self,
        blueprint: object,
        ecology_columns: dict[str, NDArray[np.float64] | NDArray[np.int64]],
        tensor_bank: list[dict[str, NDArray[np.float64]]],
        deme_variant_ids: NDArray[np.int64],
        individual_count_all: NDArray[np.float64],
        sperm_storage_all: NDArray[np.float64],
        tick: int,
        model: str = "age_structured",
        stay_after_send: bool = False,
        seed: int = 0,
    ) -> None: ...
    def refresh_deme_ecology(self, deme: int, fields: list[str], source: object) -> None: ...
    def refresh_variant_tensors(self, variant_id: int, fields: list[str], source: object) -> None: ...
    def n_variants(self) -> int: ...
    def fork_variant(self, deme: int) -> int: ...
    def set_custom_slots(self, values: object) -> None: ...
    def get_custom_slots(self) -> dict[str, bool | int | float | NDArray[np.float64]]: ...
    def set_execution_flags(self, stochastic: bool, continuous_sampling: bool, fixed_egg_count: bool, extreme_speed_mode: int) -> None: ...
    def set_hook_program(self, program: object) -> None: ...
    def clear_hook_program(self) -> None: ...
    def set_python_callbacks(
        self,
        first: list[Callable[..., int]],
        early: list[Callable[..., int]],
        late: list[Callable[..., int]],
        finish: list[Callable[..., int]] | None = None,
    ) -> None: ...
    def clear_python_callbacks(self) -> None: ...
    def reseed(self, seed: int) -> None: ...
    def drain_eco_journal(self) -> list[tuple[int, int, int, float, float]]: ...
    def set_migration_rate(self, values: NDArray[np.float64]) -> None: ...
    def capture_checkpoint(self) -> int: ...
    def restore_from_checkpoint(self, tick: int) -> int | None: ...
    def retain_checkpoints_from(self, from_tick: int) -> None: ...
    def truncate_checkpoints(self, retain_until_tick: int) -> None: ...
    def clear_checkpoints(self) -> None: ...
    def ecology_columns_snapshot(self) -> dict[str, NDArray[np.float64] | NDArray[np.int64]]: ...
    def run_tick(self) -> int: ...
    def state_snapshot(
        self,
    ) -> tuple[int, NDArray[np.float64], NDArray[np.float64]]: ...
    def set_state(
        self,
        individual_count_all: NDArray[np.float64],
        sperm_storage_all: NDArray[np.float64],
        tick: int,
    ) -> None: ...


def migrate_csr_deterministic(
    individual_count_all: NDArray[np.float64],
    sperm_storage_all: NDArray[np.float64],
    indptr: NDArray[np.int64],
    dest_idx: NDArray[np.int64],
    weights: NDArray[np.float64],
    rate: NDArray[np.float64],
    stay_after: bool,
) -> tuple[NDArray[np.float64], NDArray[np.float64]]:
    """Apply one deterministic CSR migration step."""


def migrate_csr_stochastic(
    individual_count_all: NDArray[np.float64],
    sperm_storage_all: NDArray[np.float64],
    indptr: NDArray[np.int64],
    dest_idx: NDArray[np.int64],
    weights: NDArray[np.float64],
    rate: NDArray[np.float64],
    seed: int,
    continuous_sampling: bool,
) -> tuple[NDArray[np.float64], NDArray[np.float64]]:
    """Apply one stochastic CSR migration step."""


def compute_offspring_tensor(
    meiosis: NDArray[np.float64],
    fusion: NDArray[np.float64],
) -> NDArray[np.float64]:
    """Compute the offspring probability tensor from meiosis and fusion tables."""


def equilibrium_metrics_flat(
    carrying_capacity: float,
    eggs_per_female: float,
    sex_ratio: float,
    survival_rates: NDArray[np.float64],
    reproduction_rates: NDArray[np.float64],
    fertility: NDArray[np.float64],
    competition_weights: NDArray[np.float64],
    new_adult_age: int,
    n_ages: int,
    declared_distribution: NDArray[np.float64] | None = ...,
    external_expected_eggs: float | None = ...,
) -> tuple[float, float]:
    """Compute equilibrium metrics from flat demographic inputs."""

class ParameterLog:
    """Native parameter timeline shared with session checkpoints."""
    def __init__(self) -> None: ...
    def append(self, row: tuple[int, str, float, float]) -> None: ...
    def append_detail(self, row: tuple[int, str, float, float], event: str, deme: int) -> None: ...
    def append_value(self, tick: int, name: str, old: bool | int | float | NDArray[np.float64] | None, new: bool | int | float | NDArray[np.float64] | None, event: str, deme: int) -> None: ...
    def details(self) -> list[tuple[int, str, int, str, bool | int | float | NDArray[np.float64] | None, bool | int | float | NDArray[np.float64] | None]]: ...
    def snapshot(self) -> list[tuple[int, str, float, float]]: ...
    def mark(self) -> int: ...
    def rollback(self, position: int) -> None: ...
    def clear(self) -> None: ...

class HistoryStore:
    """Native bounded numerical history storage."""
    def __init__(self, width: int, dimensions: tuple[int, ...], raw: bool, max_rows: int | None = None) -> None: ...
    max_rows: int | None
    def __len__(self) -> int: ...
    def bind_log(self, log: ParameterLog) -> None: ...
    def bind_logs(self, logs: list[ParameterLog]) -> None: ...
    def configure_observation(self, mask: NDArray[np.float64], selected: list[int], collapse_age: bool, aggregate: bool) -> None: ...
    def ticks(self) -> list[int]: ...
    def boundaries(self) -> list[tuple[int, int, str]]: ...
    def append(self, rows: NDArray[np.float64], continuation: bool = False) -> None: ...
    def query(self, start: int = 0, end: int | None = None) -> NDArray[np.float64]: ...
    def row(self, tick: int) -> NDArray[np.float64]: ...
    def clear(self) -> None: ...
    def truncate(self, tick: int) -> None: ...
    def restore_timeline(self, tick: int) -> None: ...
    def observe(self, target: HistoryStore) -> None: ...

def project_observation(ind: NDArray[np.float64], mask: NDArray[np.float64], dimensions: tuple[int, ...], selected: list[int], collapse_age: bool, aggregate: bool) -> NDArray[np.float64]:
    """Project current state with the native History observation operation."""
