#!/usr/bin/env python3
"""Generate src/natal/__init__.pyi from module-level __all__ declarations."""

from __future__ import annotations

import ast
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
PACKAGE_DIR = ROOT_DIR / "src" / "natal"
OUTPUT_FILE = PACKAGE_DIR / "__init__.pyi"


def extract_module_exports(module_file: Path) -> list[str]:
    """Return literal __all__ entries from a module source file."""
    try:
        source = module_file.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(module_file))
    except (OSError, SyntaxError):
        return []

    for node in tree.body:
        value_node = None
        if isinstance(node, ast.Assign):
            if any(isinstance(target, ast.Name) and target.id == "__all__" for target in node.targets):
                value_node = node.value
        elif isinstance(node, ast.AnnAssign):
            if isinstance(node.target, ast.Name) and node.target.id == "__all__":
                value_node = node.value

        if value_node is None:
            continue

        try:
            exports = ast.literal_eval(value_node)
        except Exception:
            return []

        if isinstance(exports, (list, tuple)) and all(isinstance(item, str) for item in exports):
            return list(exports)
        return []

    return []


def iter_public_modules(package_dir: Path) -> list[tuple[str, list[str]]]:
    """Collect public exports for each top-level package module."""
    module_exports: list[tuple[str, list[str]]] = []

    for module_file in sorted(package_dir.glob("*.py")):
        if module_file.name.startswith("_") or module_file.name == "__init__.py":
            continue

        exports = extract_module_exports(module_file)
        if exports:
            module_exports.append((module_file.stem, exports))

    return module_exports


def format_import(module_name: str, exported_names: list[str]) -> list[str]:
    """Render a stub import statement for one module."""
    single_line = f"from .{module_name} import {', '.join(exported_names)}"
    if len(single_line) <= 88:
        return [single_line]

    lines = [f"from .{module_name} import ("]
    lines.extend(f"    {name}," for name in exported_names)
    lines.append(")")
    return lines


def render_stub(module_exports: list[tuple[str, list[str]]]) -> str:
    """Render the complete __init__.pyi file content."""
    all_exports = sorted(name for _, names in module_exports for name in names)

    lines = [
        '"""Static package exports for editor tooling."""',
        "",
        "# This file is auto-generated by scripts/generate_init_pyi.py.",
        "# Do not edit it manually; re-run the generator after changing public exports.",
        "",
    ]

    for index, (module_name, exported_names) in enumerate(module_exports):
        if index:
            lines.append("")
        lines.extend(format_import(module_name, exported_names))

    lines.extend([
        "",
        "__all__ = [",
    ])
    lines.extend(f'    "{name}",' for name in all_exports)
    lines.append("]")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    module_exports = iter_public_modules(PACKAGE_DIR)
    content = render_stub(module_exports)
    OUTPUT_FILE.write_text(content, encoding="utf-8")
    export_count = sum(len(names) for _, names in module_exports)
    print(f"Wrote {OUTPUT_FILE.relative_to(ROOT_DIR)} with {export_count} exports from {len(module_exports)} modules.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
