#!/usr/bin/env python3
"""Generate src/natal/__init__.pyi from module-level __all__ declarations."""

from __future__ import annotations

import ast
from pathlib import Path
from typing import Any, Sequence, cast

ROOT_DIR = Path(__file__).resolve().parents[1]
PACKAGE_DIR = ROOT_DIR / "src" / "natal"
OUTPUT_FILE = PACKAGE_DIR / "__init__.pyi"


def extract_module_exports(module_file: Path) -> list[str]:
    """Return literal __all__ entries from a module source file."""
    try:
        source = module_file.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(module_file))
    except (OSError, SyntaxError):
        return []

    for node in tree.body:
        value_node = None
        if isinstance(node, ast.Assign):
            if any(isinstance(target, ast.Name) and target.id == "__all__" for target in node.targets):
                value_node = node.value
        elif isinstance(node, ast.AnnAssign):
            if isinstance(node.target, ast.Name) and node.target.id == "__all__":
                value_node = node.value

        if value_node is None:
            continue

        try:
            exports = ast.literal_eval(value_node)
            exports = cast(Sequence[Any], exports)
        except Exception:
            return []

        if isinstance(exports, (list, tuple)) and all(isinstance(item, str) for item in exports):
            return list(exports)
        return []

    return []


def iter_public_modules(package_dir: Path) -> list[tuple[str, list[str]]]:
    """Collect public exports for each top-level module and subpackage."""
    module_exports: list[tuple[str, list[str]]] = []

    for module_file in sorted(package_dir.glob("*.py")):
        if module_file.name.startswith("_") or module_file.name == "__init__.py":
            continue
        exports = extract_module_exports(module_file)
        if exports:
            module_exports.append((module_file.stem, exports))

    # Scan subpackages: read their __init__.py __all__
    for init_file in sorted(package_dir.glob("*/__init__.py")):
        subpkg = init_file.parent.name
        if subpkg.startswith("_"):
            continue
        exports = extract_module_exports(init_file)
        if exports:
            module_exports.append((subpkg, exports))

    return module_exports


# Names whose canonical package-level re-export is deferred through a PEP 562
# module ``__getattr__`` (import-cycle safety).  Stub resolution cannot see
# through ``__getattr__``, so these names are imported from the deeper,
# cycle-free defining module instead.  Keyed by (owning package, name) because
# a name can be legitimately re-exported by several packages.
STUB_SOURCE_REDIRECTS: dict[tuple[str, str], str] = {
    ("presets", "apply_preset_fitness_patch"): "frontend.presets._fitness",
}


def format_import(module_name: str, exported_names: list[str]) -> list[str]:
    """Render a stub import statement for one module.

    ``STUB_SOURCE_REDIRECTS`` moves individual names to a deeper, cycle-free
    module when the canonical package re-export is deferred via a module-level
    ``__getattr__`` (PEP 562), which stub resolution cannot see through.
    """
    names = sorted(exported_names)
    redirected = {
        name: target for (pkg, name), target in STUB_SOURCE_REDIRECTS.items()
        if pkg == module_name and name in names
    }
    names = [n for n in names if n not in redirected]
    rendered: list[str] = []
    if names:
        single_line = f"from .{module_name} import {', '.join(names)}"
        if len(single_line) <= 88:
            rendered.append(single_line)
        else:
            rendered.append(f"from .{module_name} import (")
            rendered.extend(f"    {name}," for name in names)
            rendered.append(")")
    for name, target in sorted(redirected.items()):
        rendered.append(f"from .{target} import {name}")
    return rendered


def render_stub(module_exports: list[tuple[str, list[str]]]) -> str:
    """Render the complete __init__.pyi file content."""
    all_exports = sorted({name for _, names in module_exports for name in names})

    lines = [
        '"""Static package exports for editor tooling."""',
        "",
        "# This file is auto-generated by scripts/generate_init_pyi.py.",
        "# Do not edit it manually; re-run the generator after changing public exports.",
        "",
    ]

    for module_name, exported_names in module_exports:
        lines.extend(format_import(module_name, exported_names))

    lines.extend([
        "",
        "__all__ = [",
    ])
    lines.extend(f'    "{name}",' for name in all_exports)
    lines.append("]")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    module_exports = iter_public_modules(PACKAGE_DIR)
    content = render_stub(module_exports)
    OUTPUT_FILE.write_text(content, encoding="utf-8")
    export_count = sum(len(names) for _, names in module_exports)
    print(f"Wrote {OUTPUT_FILE.relative_to(ROOT_DIR)} with {export_count} exports from {len(module_exports)} modules.")

    # Auto-fix ruff formatting on the generated stub.
    import subprocess
    import sys

    subprocess.run(
        [sys.executable, "-m", "ruff", "check", "--fix", str(OUTPUT_FILE)],
        capture_output=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
