#!/usr/bin/env python3
"""Generate src/natal/__init__.pyi from the explicit public export list.

The list lives in ``src/natal/__init__.py`` as ``_PUBLIC_EXPORTS`` (plan S6,
must-not-exist item 8); the consistency test in ``tests/test_phase0_shims.py``
pins it against the modules' literal ``__all__``.  Importing ``natal`` is
lazy-safe (no child-module execution), so the generator reads the list at
runtime instead of re-scanning the tree."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import cast

ROOT_DIR = Path(__file__).resolve().parents[1]
PACKAGE_DIR = ROOT_DIR / "src" / "natal"
OUTPUT_FILE = PACKAGE_DIR / "__init__.pyi"


def iter_public_modules(package_dir: Path) -> list[tuple[str, list[str]]]:
    """Read the explicit public export list from the installed package.

    Dotted owner names (e.g. ``frontend.hooks``) map to the real package
    paths so the generated stub imports resolve.
    """
    import sys

    sys.path.insert(0, str(ROOT_DIR / "src"))
    import natal  # noqa: PLC0415 — the explicit list IS the source of truth

    # These typed runtime declarations are intentionally absent from the public stub.
    exports = cast(dict[str, list[str]], vars(natal)["_PUBLIC_EXPORTS"])
    owners = cast(dict[str, str], vars(natal)["_lazy_map"])
    # Multiple units may re-export the same object. Match the first owner used
    # by the runtime lazy map, rather than emitting duplicate stub bindings.
    return sorted(
        (unit, [name for name in names if owners[name] == unit])
        for unit, names in exports.items()
    )


# Names whose canonical package-level re-export is deferred through a PEP 562
# module ``__getattr__`` (import-cycle safety).  Stub resolution cannot see
# through ``__getattr__``, so these names are imported from the deeper,
# cycle-free defining module instead.  Keyed by (owning package, name) because
# a name can be legitimately re-exported by several packages.
STUB_SOURCE_REDIRECTS: dict[tuple[str, str], str] = {
    ("frontend.presets", "apply_preset_fitness_patch"): "frontend.presets._fitness",
}


def format_import(module_name: str, exported_names: list[str]) -> list[str]:
    """Render a stub import statement for one module.

    ``STUB_SOURCE_REDIRECTS`` moves individual names to a deeper, cycle-free
    module when the canonical package re-export is deferred via a module-level
    ``__getattr__`` (PEP 562), which stub resolution cannot see through.
    """
    names = sorted(exported_names)
    redirected = {
        name: target for (pkg, name), target in STUB_SOURCE_REDIRECTS.items()
        if pkg == module_name and name in names
    }
    names = [n for n in names if n not in redirected]
    rendered: list[str] = []
    if names:
        single_line = f"from .{module_name} import {', '.join(names)}"
        if len(single_line) <= 88:
            rendered.append(single_line)
        else:
            rendered.append(f"from .{module_name} import (")
            rendered.extend(f"    {name}," for name in names)
            rendered.append(")")
    for name, target in sorted(redirected.items()):
        rendered.append(f"from .{target} import {name}")
    return rendered


def render_stub(module_exports: list[tuple[str, list[str]]]) -> str:
    """Render the complete __init__.pyi file content."""
    all_exports = sorted({name for _, names in module_exports for name in names})

    lines = [
        '"""Static package exports for editor tooling."""',
        "",
        "# This file is auto-generated by scripts/generate_init_pyi.py.",
        "# Do not edit it manually; re-run the generator after changing public exports.",
        "",
    ]

    for module_name, exported_names in module_exports:
        lines.extend(format_import(module_name, exported_names))

    lines.extend([
        "",
        "__all__ = [",
    ])
    lines.extend(f'    "{name}",' for name in all_exports)
    lines.append("]")
    lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Generate or check the formatted stub without changing it in check mode."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    module_exports = iter_public_modules(PACKAGE_DIR)
    content = render_stub(module_exports)
    # Format in memory so a failed check never overwrites a developer's stub.
    formatted = subprocess.run(
        [sys.executable, "-m", "ruff", "check", "--fix", "--stdin-filename", str(OUTPUT_FILE), "-"],
        input=content, capture_output=True, text=True, cwd=ROOT_DIR, check=False,
    )
    if formatted.returncode:
        print(formatted.stderr, file=sys.stderr)
        return formatted.returncode
    content = formatted.stdout
    if args.check:
        if not OUTPUT_FILE.exists() or OUTPUT_FILE.read_text(encoding="utf-8") != content:
            print("Public stub is out of date; run python scripts/generate_init_pyi.py.")
            return 1
        print("Public stub is up to date.")
        return 0
    OUTPUT_FILE.write_text(content, encoding="utf-8")
    export_count = sum(len(names) for _, names in module_exports)
    print(f"Wrote {OUTPUT_FILE.relative_to(ROOT_DIR)} with {export_count} exports from {len(module_exports)} modules.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
