"""Hook subsystem public API."""

from .entry.declarative import (
    Op,
    compile_declarative_hook,
    parse_condition,
)
from .entry.decorator import hook
from .entry.selector import compile_selector_callback
from .tick_context import BlueprintView, HookRunner, TickContext, TickMetrics
from .types import (
    COND_ALWAYS,
    COND_OP_AND,
    COND_OP_NOT,
    COND_OP_OR,
    COND_TICK_EQ,
    COND_TICK_GE,
    COND_TICK_GT,
    COND_TICK_LE,
    COND_TICK_LT,
    COND_TICK_MOD,
    ECO_PARAM_NAMES,
    EVENT_EARLY,
    EVENT_FINISH,
    EVENT_FIRST,
    EVENT_ID_MAP,
    EVENT_LATE,
    EVENT_NAMES,
    NUM_EVENTS,
    RESULT_CONTINUE,
    RESULT_SKIP,
    RESULT_STOP,
    CompiledHookDescriptor,
    CompiledHookPlan,
    DemeSelector,
    HookOp,
    HookProgram,
    OpType,
    RunProgram,
    deme_selector_matches,
    empty_hook_program,
)

__all__ = [
    "OpType",
    "DemeSelector",
    "deme_selector_matches",
    "HookOp",
    "Op",
    "CompiledHookPlan",
    "CompiledHookDescriptor",
    "HookProgram",
    "RunProgram",
    "empty_hook_program",
    "hook",
    "compile_declarative_hook",
    "compile_selector_callback",
    "TickContext",
    "TickMetrics",
    "BlueprintView",
    "HookRunner",
    "COND_ALWAYS",
    "COND_TICK_EQ",
    "COND_TICK_MOD",
    "ECO_PARAM_NAMES",
    "COND_TICK_GE",
    "COND_TICK_GT",
    "COND_TICK_LE",
    "COND_TICK_LT",
    "COND_OP_AND",
    "COND_OP_OR",
    "COND_OP_NOT",
    "EVENT_FIRST",
    "EVENT_EARLY",
    "EVENT_LATE",
    "EVENT_FINISH",
    "EVENT_NAMES",
    "EVENT_ID_MAP",
    "NUM_EVENTS",
    "RESULT_CONTINUE",
    "RESULT_SKIP",
    "RESULT_STOP",
    "parse_condition",
]
