"""Hook subsystem public API."""

from .compiler import (
    _njit_switch,
    CompiledEventHooks,
    compile_combined_hook,
    hook,
    noop_hook,
)
from .declarative import (
    Op,
    _parse_condition,
    compile_declarative_hook,
)
from .executor import (
    HookExecutor,
    _eval_csr_condition_program,
    build_hook_program,
    deme_selector_matches,
    execute_csr_event_arrays,
    execute_csr_event_program,
    execute_csr_event_program_with_state,
)
from .selector import compile_selector_hook
from .types import (
    DemeSelector,
        HookOp,
        OpType,
    COND_ALWAYS,
    COND_OP_AND,
    COND_OP_NOT,
    COND_OP_OR,
    COND_TICK_EQ,
    COND_TICK_GE,
    COND_TICK_GT,
    COND_TICK_LE,
    COND_TICK_LT,
    COND_TICK_MOD,
    EVENT_EARLY,
    EVENT_FINISH,
    EVENT_FIRST,
    EVENT_ID_MAP,
    EVENT_LATE,
    EVENT_NAMES,
    NUM_EVENTS,
    RESULT_CONTINUE,
    RESULT_STOP,
    CompiledHookDescriptor,
    CompiledHookPlan,
    HookProgram,
)

__all__ = [
    "OpType",
    "DemeSelector",
    "deme_selector_matches",
    "HookOp",
    "Op",
    "CompiledHookPlan",
    "CompiledHookDescriptor",
    "HookProgram",
    "HookExecutor",
    "execute_csr_event_arrays",
    "execute_csr_event_program_with_state",
    "execute_csr_event_program",
    "build_hook_program",
    "noop_hook",
    "compile_combined_hook",
    "CompiledEventHooks",
    "hook",
    "compile_declarative_hook",
    "compile_selector_hook",
    "COND_ALWAYS",
    "COND_TICK_EQ",
    "COND_TICK_MOD",
    "COND_TICK_GE",
    "COND_TICK_GT",
    "COND_TICK_LE",
    "COND_TICK_LT",
    "COND_OP_AND",
    "COND_OP_OR",
    "COND_OP_NOT",
    "EVENT_FIRST",
    "EVENT_EARLY",
    "EVENT_LATE",
    "EVENT_FINISH",
    "EVENT_NAMES",
    "EVENT_ID_MAP",
    "NUM_EVENTS",
    "RESULT_CONTINUE",
    "RESULT_STOP",
    "_njit_switch",
    "_parse_condition",
    "_eval_csr_condition_program",
]
