"""CSR execution engine and Python-level hook executor.

This module is the runtime heart of the hook system. It provides two
dispatch paths for declarative (CSR) and custom hooks:

**Numba fast path (compiled kernel)**
  ``execute_csr_event_arrays`` and ``_execute_single_csr_hook`` operate
  on flattened ``HookProgram`` arrays. The lifecycle templates
  (``engine/templates/*.tmpl.py``) call these directly, or call unified
  dispatch functions generated by ``compiler.compile_unified_event_hook``
  when CSR and njit hooks are mixed.

**Python fallback path (``HookExecutor``)**
  Used when Numba is disabled. Descriptors are sorted by ``priority``
  and executed sequentially — CSR ops via ``execute_csr_event_arrays``,
  njit functions by direct call, and py_wrapper functions by callable
  invocation.

----
Return value protocol
----
Every hook execution function returns an ``int`` following this convention:

  ``RESULT_CONTINUE`` (0)
      All operations completed successfully; proceed to the next hook.
  ``RESULT_SKIP`` (0, alias for readability)
      This hook is not applicable in the current context (e.g. wrong
      deme, out-of-bounds index).  Callers treat it identically to
      ``RESULT_CONTINUE`` — the distinction is for human readers only.
  ``RESULT_STOP`` (1)
      A ``stop_if_*`` operation triggered or the hook signalled an abort.
      The current *event* is immediately terminated; subsequent hooks
      for the same event are skipped. The next event (e.g. ``early``
      after ``first``) still executes normally.

----
Data structures in play
----

``HookProgram`` (NamedTuple)
    All declarative hooks packed into flat CSR arrays.  Three-level
    indexing: event → hook → op.  ``hook_offsets[event_id]`` gives the
    hook range; ``op_offsets[hook_idx]`` gives the op range.

``CompiledHookPlan`` (dataclass)
    A single declarative hook's ops, already resolved to concrete
    integer indices.  Stored as a ``plan`` field on
    ``CompiledHookDescriptor``.

``CompiledHookDescriptor`` (dataclass)
    One descriptor per registered hook.  Exactly one of ``plan``
    (CSR), ``njit_fn`` (compiled custom), or ``py_wrapper`` (Python)
    is the active payload.

----
Sperm storage awareness
----
Age-structured populations carry a ``sperm_storage`` array.  When a
female count is reduced (e.g. by ``Op.scale`` or ``Op.kill``), the
sperm categories must be scaled by the same survival rate to remain
coherent.  Discrete-generation populations have no sperm storage
(``has_sperm_storage=False``) and all operations use the simpler
``_apply_target_without_sperm`` path.

----
The hot loop is intentionally array-driven and avoids Python objects.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Dict, List

import numpy as np

from natal import numba_compat as nbc
from natal.numba_utils import njit_switch

from .types import (
    COND_OP_AND,
    COND_OP_NOT,
    COND_OP_OR,
    COND_TICK_GT,
    EVENT_ID_MAP,
    NUM_EVENTS,
    RESULT_CONTINUE,
    RESULT_SKIP,
    RESULT_STOP,
    CompiledHookDescriptor,
    DemeSelector,
    HookProgram,
)

if TYPE_CHECKING:
    from natal.base_population import BasePopulation


# ---------------------------------------------------------------------------
# Deme selector helpers
# ---------------------------------------------------------------------------


def deme_selector_matches(selector: DemeSelector, deme_id: int) -> bool:
    """Return whether *deme_id* should execute under *selector* (Python path).

    Supported forms:
      - ``"*"`` — all demes (wildcard)
      - ``int`` — single deme
      - ``list`` / ``tuple`` / ``range`` — set of demes
    """
    if selector == "*":
        return True
    if isinstance(selector, int):
        return selector == deme_id
    if isinstance(selector, range):
        return deme_id in selector
    # list or tuple
    return deme_id in selector


@njit_switch(cache=True)
def njit_deme_selector_matches(
    sel_type: int,
    start: int,
    end: int,
    data: np.ndarray,
    deme_id: int,
) -> bool:
    """Numba-compatible deme selector check operating on serialised arrays.

    The selector is encoded in the HookProgram's ``deme_selector_*`` arrays:

    ==========  ============================================
    sel_type    Meaning
    ==========  ============================================
    0           ``"*"`` (ANY) — always True
    1           single integer — ``data[start] == deme_id``
    2           ``range`` — ``start <= deme_id < end``
    3           list/tuple — iterate ``data[start:end]``
    ==========  ============================================
    """
    if sel_type == 0:  # ANY — wildcard, matches every deme
        return True
    if sel_type == 1:  # SINGLE — one explicit deme id
        return data[start] == deme_id
    if sel_type == 2:  # RANGE — contiguous block of demes
        return deme_id >= data[start] and deme_id < data[start + 1]
    if sel_type == 3:  # LIST — sparse set, linear scan
        if start >= end:
            return False
        for i in range(start, end):
            if data[i] == deme_id:
                return True
        return False
    return True  # Unknown type — allow (conservative)


# ---------------------------------------------------------------------------
# CSR condition evaluation (RPN — Reverse Polish Notation)
# ---------------------------------------------------------------------------

# Condition token type constants (inlined for njit scope to avoid
# attribute lookup).  Values must match types.py:COND_*.
# Atomic predicates:     0..6  → evaluated by _check_csr_condition
# Logical operators:   100..102 → evaluated by the RPN stack machine
# (COND_OP_AND, COND_OP_OR, COND_OP_NOT are already imported above.)
_COND_ALWAYS = 0
_COND_TICK_EQ = 1
_COND_TICK_MOD = 2
_COND_TICK_GE = 3
_COND_TICK_LT = 4
_COND_TICK_LE = 5
_COND_TICK_GT = 6


@njit_switch(cache=True)
def _check_csr_condition(cond_type: int, cond_param: int, tick: int) -> bool:
    """Evaluate a single atomic condition token against the current tick.

    Each declarative op can have a ``when`` clause (e.g. ``"tick >= 100"``).
    The clause is parsed into an RPN token stream.  This function handles
    the *leaf* tokens — comparisons like ``tick == 5`` or ``tick % 3 == 0``.

    Logical operators (AND/OR/NOT) have higher token values and are handled
    by ``_eval_csr_condition_program`` instead.
    """
    if cond_type == _COND_ALWAYS:    # always True (no when clause)
        return True
    if cond_type == _COND_TICK_EQ:   # tick == N
        return tick == cond_param
    if cond_type == _COND_TICK_MOD:  # tick % N == 0 (periodic)
        return cond_param > 0 and tick % cond_param == 0
    if cond_type == _COND_TICK_GE:   # tick >= N
        return tick >= cond_param
    if cond_type == _COND_TICK_LT:   # tick < N
        return tick < cond_param
    if cond_type == _COND_TICK_LE:   # tick <= N
        return tick <= cond_param
    if cond_type == _COND_TICK_GT:   # tick > N
        return tick > cond_param
    # Logical operators (AND/OR/NOT) should never reach the atomic
    # evaluator — they're handled by the RPN stack machine.
    # If one does appear, treat it as False (conservative).
    if cond_type >= COND_OP_AND:
        return False
    return True


@njit_switch(cache=True)
def _eval_csr_condition_program(
    cond_types: np.ndarray,
    cond_params: np.ndarray,
    cond_start: int,
    cond_end: int,
    tick: int,
) -> bool:
    """Evaluate an RPN condition program spanning ``[cond_start, cond_end)``.

    Each declarative operation's ``when`` clause is compiled to a
    postfix (RPN) token stream and stored in the flattened
    ``condition_types_data`` / ``condition_params_data`` arrays.
    ``cond_start`` and ``cond_end`` isolate one operation's tokens.

    The evaluation uses an int8 stack — compact, fast, and njit-safe.
    Leaf tokens (``tick == 5``, etc.) push 0 or 1 onto the stack.
    Logical operators (AND, OR, NOT) pop operands and push the result.

    Returns:
        True if the condition is satisfied (or if no condition exists),
        False otherwise.
    """
    max_len = cond_end - cond_start
    if max_len <= 0:
        return True  # No condition → always execute

    # int8 stack: values are only ever 0 or 1, footprint is minimal.
    stack = np.zeros(max_len + 1, dtype=np.int8)
    top = 0  # Next free slot (points one past the last pushed value)

    for idx in range(cond_start, cond_end):
        token_type = cond_types[idx]
        token_param = cond_params[idx]

        # --- Leaf: atomic predicate → push 0 or 1 ---
        if token_type <= COND_TICK_GT:
            val = 1 if _check_csr_condition(token_type, token_param, tick) else 0
            stack[top] = val
            top += 1
            continue

        # --- Logical NOT: pop one, negate, push ---
        if token_type == COND_OP_NOT:
            if top < 1:
                return False  # Malformed program — not enough operands
            stack[top - 1] = 0 if stack[top - 1] else 1
            continue

        # --- Logical AND: pop two, AND, push ---
        if token_type == COND_OP_AND:
            if top < 2:
                return False
            rhs = stack[top - 1]
            lhs = stack[top - 2]
            top -= 2
            stack[top] = 1 if (lhs and rhs) else 0
            top += 1
            continue

        # --- Logical OR: pop two, OR, push ---
        if token_type == COND_OP_OR:
            if top < 2:
                return False
            rhs = stack[top - 1]
            lhs = stack[top - 2]
            top -= 2
            stack[top] = 1 if (lhs or rhs) else 0
            top += 1
            continue

        # Unknown token — conservative: fail
        return False

    # After evaluating all tokens, the stack should contain exactly one value.
    if top != 1:
        return False
    return stack[0] != 0


# Public alias for tests and external consumers.
eval_csr_condition_program = _eval_csr_condition_program


# ---------------------------------------------------------------------------
# Target-count application helpers
# ---------------------------------------------------------------------------
# Hook operations express a *target count* (e.g. "set to 20" or "scale by 0.5").
# Applying the target involves either adding individuals (if target > current)
# or removing them (if target < current).  Removal is modelled as *survival* —
# each individual survives with probability = target / current.  This keeps
# the semantics of ``Op.scale(0.5)`` identical to "50% survival" and ensures
# sperm storage scaling stays coherent.


@njit_switch(cache=True)
def _sample_survivors(
    n_base: float,
    survival_prob: float,
    stochastic_flag: bool,
    dirichlet_flag: bool,
) -> float:
    """Return the survivor count after applying *survival_prob* to *n_base*.

    Args:
        n_base: Current count (may be fractional for continuous models).
        survival_prob: Per-individual survival probability in [0, 1].
        stochastic_flag: If False, use deterministic rounding.
        dirichlet_flag: If True, keep counts continuous (no integer rounding).

    Returns:
        Survivor count — continuous if *dirichlet_flag*, else integer-rounded.
    """
    if n_base <= 0.0:
        return 0.0
    if stochastic_flag:
        if dirichlet_flag:
            # Continuous-Dirichlet sampling (no discrete rounding).
            return nbc.continuous_binomial(n_base, survival_prob)
        # Discrete binomial: round count, then sample.
        return float(np.random.binomial(int(round(n_base)), survival_prob))
    # Deterministic: simply multiply.
    return n_base * survival_prob


@njit_switch(cache=True)
def _apply_target_without_sperm(
    current_count: float,
    target_count: float,
    stochastic_flag: bool,
    dirichlet_flag: bool,
) -> float:
    """Apply a target count update for populations *without* sperm storage.

    This is the simpler path — used for males in all models and for all
    individuals in discrete-generation models (which have no sperm storage).

    If *target_count* >= *current_count*, individuals are *added* (the
    count simply increases).  If *target_count* < *current_count*, a
    survival process is applied with probability = target / current.
    """
    if stochastic_flag and not dirichlet_flag:
        # Integer-count stochastic: round before survival sampling.
        current_count = float(round(current_count))

    if target_count >= current_count:
        # Adding individuals — no survival semantics needed.
        return target_count
    if current_count <= 0.0:
        return 0.0

    survival_prob = max(0.0, min(1.0, target_count / current_count))
    return _sample_survivors(current_count, survival_prob, stochastic_flag, dirichlet_flag)


@njit_switch(cache=True)
def _apply_target_with_sperm(
    current_count: float,
    target_count: float,
    sperm_row: np.ndarray,
    stochastic_flag: bool,
    dirichlet_flag: bool,
) -> float:
    """Apply a target count update for female branch with sperm storage.

    This is the complex path — used for age-structured models where
    female counts are linked to sperm category counts.  When reducing
    the female count, sperm categories are scaled (or sampled) by the
    **same survival rate**, keeping the population state coherent.

    The female count is conceptually split into *virgins* (no stored
    sperm) and *mated* (one entry per gamete-male genotype).  Each
    subgroup survives independently, then the survivors are summed
    back into the total female count.

    Args:
        current_count: Total female count before the operation.
        target_count: Desired female count after the operation.
        sperm_row: ``sperm_storage[age, gidx, :]`` — per-genotype-male
            sperm counts for this (age, female-genotype) cell.
        stochastic_flag: If False, deterministic.
        dirichlet_flag: If True, continuous sampling.

    Returns:
        New total female count = surviving virgins + surviving mated.
    """
    if stochastic_flag and not dirichlet_flag:
        current_count = float(round(current_count))

    if target_count >= current_count:
        # Adding females — sperm storage unchanged.
        return target_count

    if current_count <= 0.0:
        # Extinction — clear all sperm entries.
        for gm_idx in range(sperm_row.shape[0]):
            sperm_row[gm_idx] = 0.0
        return 0.0

    survival_prob = max(0.0, min(1.0, target_count / current_count))

    # --- Deterministic: proportionally scale sperm and total ---
    if not stochastic_flag:
        for gm_idx in range(sperm_row.shape[0]):
            sperm_row[gm_idx] *= survival_prob
        return target_count

    # --- Stochastic: sample each sperm category independently ---
    n_f_raw = float(current_count)

    # Total sperm across all gamete-male genotypes.
    total_sperm_count = 0.0
    for gm_idx in range(sperm_row.shape[0]):
        total_sperm_count += float(sperm_row[gm_idx])

    # Virgin count = total females - mated females.
    n_virgins_raw = n_f_raw - total_sperm_count
    if n_virgins_raw >= -nbc.EPS:
        n_virgins_raw = max(0.0, n_virgins_raw)
    if n_virgins_raw < 0.0:
        # Inconsistent state — should never happen in normal simulation.
        print(
            "n_virgins<0 in _apply_target_with_sperm:",
            n_virgins_raw,
            "n_f_raw=",
            n_f_raw,
            "total_sperm=",
            total_sperm_count,
        )
        raise ValueError("Invalid state: n_virgins < 0 in _apply_target_with_sperm")

    # Round for discrete sampling if not in continuous mode.
    n_virgins = n_virgins_raw if dirichlet_flag else float(int(round(n_virgins_raw)))

    # Sample each sperm category with the same survival probability.
    new_sperm_sum = 0.0
    for gm_idx in range(sperm_row.shape[0]):
        if dirichlet_flag:
            n_sperm = sperm_row[gm_idx]
        else:
            n_sperm = float(int(round(sperm_row[gm_idx])))

        sperm_row[gm_idx] = _sample_survivors(n_sperm, survival_prob, True, dirichlet_flag)
        new_sperm_sum += sperm_row[gm_idx]

    # Sample virgins.
    survivors_virgins = _sample_survivors(n_virgins, survival_prob, True, dirichlet_flag)

    # New total = surviving mated + surviving virgins.
    return new_sperm_sum + survivors_virgins


# ===================================================================
# Declarative CSR execution — the hot loop
# ===================================================================
# These functions are the most performance-critical code in the hook
# system.  They iterate over flattened arrays, evaluate conditions,
# compute target counts, and mutate ``individual_count`` (and
# ``sperm_storage``) in-place.
#
# Architecture note — two callable granularities:
#
#   ``_execute_single_csr_hook(hook_idx, ...)``
#       Executes ONE hook at a global index.  Extracted from the
#       inner loop of ``execute_csr_event_arrays`` so that unified
#       mixed-type dispatch (CSR + njit interleaved by priority)
#       can call individual CSR hooks at arbitrary positions.
#
#   ``execute_csr_event_arrays(event_id, ...)``
#       Executes ALL hooks for one event.  Used by lifecycle
#       templates and by ``HookExecutor`` (Python fallback).
#       Refactored to delegate each hook to ``_execute_single_csr_hook``.
# ===================================================================


# OpType enum values (inlined for njit scope — avoids attribute lookup).
_OP_SCALE = 0
_OP_SET = 1
_OP_ADD = 2
_OP_SUBTRACT = 3
_OP_KILL = 4
_OP_SAMPLE = 5
_OP_STOP_IF_ZERO = 6
_OP_STOP_IF_BELOW = 7
_OP_STOP_IF_ABOVE = 8
_OP_STOP_IF_EXTINCTION = 9


@njit_switch(cache=True)
def _execute_single_csr_hook(
    hook_idx: int,
    n_hooks: int | np.integer[Any],
    op_offsets: np.ndarray,
    op_types_data: np.ndarray,
    gidx_offsets_data: np.ndarray,
    gidx_data: np.ndarray,
    age_offsets_data: np.ndarray,
    age_data: np.ndarray,
    sex_masks_data: np.ndarray,
    params_data: np.ndarray,
    condition_offsets_data: np.ndarray,
    condition_types_data: np.ndarray,
    condition_params_data: np.ndarray,
    deme_selector_types: np.ndarray,
    deme_selector_offsets: np.ndarray,
    deme_selector_data: np.ndarray,
    individual_count: np.ndarray,
    sperm_storage: np.ndarray,
    has_sperm_storage: bool,
    tick: int,
    stochastic: bool,
    continuous_sampling: bool,
    deme_id: int,
) -> int:
    """Execute a single CSR hook at global index *hook_idx*.

    This function is the **per-hook CSR primitive**.  Given a global
    ``hook_idx`` into the flattened ``HookProgram`` arrays, it:

    1. Checks that *hook_idx* is in bounds.  Returns ``RESULT_SKIP``
       if not.
    2. Checks the serialised deme selector for this hook.  Returns
       ``RESULT_SKIP`` if the current *deme_id* doesn't match.
    3. Iterates over the hook's operations (derived from
       ``op_offsets[hook_idx]`` to ``op_offsets[hook_idx + 1]``).
    4. For each operation:
       a. Evaluates the RPN condition program (``when`` clause).
          Skips the op if the condition is not met.
       b. Reads the operation type and parameter.
       c. Reads the genotype / age / sex selectors (CSR ranges).
       d. For each selected (sex, age, genotype) cell:
          - Computes a *target count* from the operation type.
          - Applies the target via ``_apply_target_with_sperm`` or
            ``_apply_target_without_sperm``, depending on sex and
            whether sperm storage exists.
       e. For ``stop_if_*`` operations, aggregates the selected cells
          and returns ``RESULT_STOP`` if the condition is met.
    5. Returns ``RESULT_CONTINUE`` if all operations completed normally.

    Why this function exists as a standalone primitive
    ---------------------------------------------------
    Before this was extracted, ``execute_csr_event_arrays`` bundled the
    hook loop and the op loop together.  That made it impossible to
    interleave CSR hooks with njit hooks by priority — you could only
    execute ALL CSR hooks for an event as one batch.

    Now the unified dispatch (``compiler.compile_unified_event_hook``)
    generates a function that calls ``_execute_single_csr_hook`` at
    specific positions in a priority-ordered schedule, alternating
    with njit function calls.

    Returns:
        ``RESULT_CONTINUE`` (0) — all ops executed normally.
        ``RESULT_SKIP`` (0)     — hook not applicable (wrong deme / OOB).
        ``RESULT_STOP`` (1)     — a ``stop_if_*`` operation triggered.
    """
    # --- Guard: bounds check ---
    if hook_idx < 0 or hook_idx >= n_hooks:
        return RESULT_SKIP

    # --- Guard: deme selector ---
    # Each hook stores a serialised selector in deme_selector_types/offsets/data.
    # The selector encoding is: 0=ANY, 1=SINGLE, 2=RANGE, 3=LIST.
    if not njit_deme_selector_matches(
        deme_selector_types[hook_idx],
        deme_selector_offsets[hook_idx],
        deme_selector_offsets[hook_idx + 1],
        deme_selector_data,
        deme_id,
    ):
        return RESULT_SKIP

    # --- Op range for this hook ---
    # op_offsets is a CSR-style prefix-sum array: op_offsets[i] is the
    # start index of hook i's ops in the flattened op_*_data arrays.
    op_start = op_offsets[hook_idx]
    op_end = op_offsets[hook_idx + 1]

    for op_idx in range(op_start, op_end):
        # ---- Condition evaluation ----
        cond_start = condition_offsets_data[op_idx]
        cond_end = condition_offsets_data[op_idx + 1]

        if not _eval_csr_condition_program(
            condition_types_data,
            condition_params_data,
            cond_start,
            cond_end,
            tick,
        ):
            continue  # Condition not met — skip this operation entirely.

        op_type = op_types_data[op_idx]
        param = params_data[op_idx]

        # ---- Genotype / age / sex selectors (CSR ranges) ----
        gidx_start = gidx_offsets_data[op_idx]
        gidx_end = gidx_offsets_data[op_idx + 1]
        age_start = age_offsets_data[op_idx]
        age_end = age_offsets_data[op_idx + 1]

        # sex_masks_data is a flat array: [f0, m0, f1, m1, ...]
        # Each operation contributes 2 bools (female, male).
        sex_mask_idx = op_idx * 2
        sex_female = sex_masks_data[sex_mask_idx]
        sex_male = sex_masks_data[sex_mask_idx + 1]

        # ---- Iterate over selected cells (sex × age × genotype) ----
        for sex_idx in range(2):
            if sex_idx == 0 and not sex_female:
                continue
            if sex_idx == 1 and not sex_male:
                continue

            for age_idx_ptr in range(age_start, age_end):
                age = age_data[age_idx_ptr]

                for gidx_ptr in range(gidx_start, gidx_end):
                    gidx = gidx_data[gidx_ptr]
                    current = individual_count[sex_idx, age, gidx]

                    # ---- Compute target count from operation type ----
                    # Each operation specifies a *target count* for the
                    # selected cells.  The target is then applied via one
                    # of the two _apply_target_* helpers.
                    if op_type == _OP_SCALE:
                        target = max(0.0, current * param)
                    elif op_type == _OP_SET:
                        target = max(0.0, param)
                    elif op_type == _OP_ADD:
                        target = max(0.0, current + param)
                    elif op_type == _OP_SUBTRACT:
                        target = max(0.0, current - param)
                    elif op_type == _OP_KILL:
                        # kill(prob=p) → scale by (1-p)
                        target = max(0.0, current * (1.0 - param))
                    elif op_type == _OP_SAMPLE:
                        # sample(size=n) → clamp to at most n
                        target = min(current, max(0.0, param))
                    else:
                        target = current  # Unknown op — no-op

                    # ---- Apply target to cell ----
                    # Only mutation operations (0..5) modify individual_count.
                    # STOP_IF operations (6..9) are handled after the cell loop.
                    if op_type <= _OP_SAMPLE:
                        if sex_idx == 0 and has_sperm_storage:
                            # Female + sperm storage: scale sperm too.
                            individual_count[sex_idx, age, gidx] = _apply_target_with_sperm(
                                current,
                                target,
                                sperm_storage[age, gidx, :],
                                stochastic,
                                continuous_sampling,
                            )
                        else:
                            # Male or no sperm storage: simple survival.
                            individual_count[sex_idx, age, gidx] = _apply_target_without_sperm(
                                current,
                                target,
                                stochastic,
                                continuous_sampling,
                            )

        # ---- STOP_IF operations: aggregate and check threshold ----
        # These run AFTER the cell loop because they aggregate the
        # (possibly modified) selected cells to decide whether to abort.
        if op_type == _OP_STOP_IF_ZERO or op_type == _OP_STOP_IF_BELOW or op_type == _OP_STOP_IF_ABOVE:
            selected_total = 0.0
            for sex_idx in range(2):
                if sex_idx == 0 and not sex_female:
                    continue
                if sex_idx == 1 and not sex_male:
                    continue

                for age_idx_ptr in range(age_start, age_end):
                    age = age_data[age_idx_ptr]
                    for gidx_ptr in range(gidx_start, gidx_end):
                        gidx = gidx_data[gidx_ptr]
                        selected_total += individual_count[sex_idx, age, gidx]

            if op_type == _OP_STOP_IF_ZERO and selected_total <= 0.0:
                return RESULT_STOP
            if op_type == _OP_STOP_IF_BELOW and selected_total < param:
                return RESULT_STOP
            if op_type == _OP_STOP_IF_ABOVE and selected_total > param:
                return RESULT_STOP
        elif op_type == _OP_STOP_IF_EXTINCTION:
            # Global extinction check — not scoped to selected cells.
            if individual_count.sum() <= 0.0:
                return RESULT_STOP

    return RESULT_CONTINUE


# Public alias — imported by ``compiler.compile_unified_event_hook``
# and available for tests.
execute_single_csr_hook = _execute_single_csr_hook


@njit_switch(cache=True)
def execute_csr_event_arrays(
    n_events: int | np.integer[Any],
    n_hooks: int | np.integer[Any],
    hook_offsets: np.ndarray,
    # n_ops_list is unpacked from HookProgram by positional callers
    # (execute_csr_event_program_with_state, HookExecutor) but not
    # consumed inside this function — it exists only in the HookProgram
    # for introspection / debugging.
    n_ops_list: np.ndarray,  # pyright: ignore[reportUnusedParameter]
    op_offsets: np.ndarray,
    op_types_data: np.ndarray,
    gidx_offsets_data: np.ndarray,
    gidx_data: np.ndarray,
    age_offsets_data: np.ndarray,
    age_data: np.ndarray,
    sex_masks_data: np.ndarray,
    params_data: np.ndarray,
    condition_offsets_data: np.ndarray,
    condition_types_data: np.ndarray,
    condition_params_data: np.ndarray,
    deme_selector_types: np.ndarray,
    deme_selector_offsets: np.ndarray,
    deme_selector_data: np.ndarray,
    event_id: int,
    individual_count: np.ndarray,
    sperm_storage: np.ndarray,
    has_sperm_storage: bool,
    tick: int,
    stochastic: bool,
    continuous_sampling: bool,
    deme_id: int,
) -> int:
    """Execute ALL hooks for one event from flattened CSR arrays.

    This is the **batch CSR dispatch** function — it resolves
    *event_id* to a hook range via ``hook_offsets``, then calls
    ``_execute_single_csr_hook`` for each hook in that range.

    Inputs are plain ndarrays extracted from ``HookProgram`` (a
    NamedTuple).  The function signature mirrors HookProgram's fields
    positionally so callers can unpack the tuple directly.

    Three-level CSR traversal
    -------------------------
    ::

        event_id  ──►  hook_offsets[event_id]  ──►  hook range
        hook_idx  ──►  op_offsets[hook_idx]    ──►  op range
        op_idx    ──►  gidx_offsets[op_idx]    ──►  cell range
                       age_offsets[op_idx]
                       condition_offsets[op_idx]

    Returns:
        ``RESULT_CONTINUE`` (0) — all hooks executed normally.
        ``RESULT_STOP`` (1)     — a hook returned STOP.
    """
    if event_id < 0 or event_id >= n_events:
        return 0  # Out-of-bounds event — no-op

    # hook_offsets is a prefix-sum: hook_offsets[event_id] is the
    # first hook for this event, hook_offsets[event_id + 1] is one
    # past the last.
    hook_start = hook_offsets[event_id]
    hook_end = hook_offsets[event_id + 1]

    for hook_idx in range(hook_start, hook_end):
        result = _execute_single_csr_hook(
            hook_idx, n_hooks, op_offsets,
            op_types_data, gidx_offsets_data, gidx_data,
            age_offsets_data, age_data, sex_masks_data, params_data,
            condition_offsets_data, condition_types_data, condition_params_data,
            deme_selector_types, deme_selector_offsets, deme_selector_data,
            individual_count, sperm_storage, has_sperm_storage,
            tick, stochastic, continuous_sampling, deme_id,
        )
        # Propagate STOP immediately — don't execute subsequent hooks.
        if result != RESULT_CONTINUE:
            return result

    return RESULT_CONTINUE


def build_hook_program(program: HookProgram) -> HookProgram:
    """Compatibility hook for future HookProgram validation/migration.

    Currently a no-op that returns the program unchanged.  Exists as
    a hook point for potential schema upgrades or validation logic.
    """
    return program


@njit_switch(cache=True)
def execute_csr_event_program_with_state(
    program: HookProgram,
    event_id: int,
    individual_count: np.ndarray,
    sperm_storage: np.ndarray,
    tick: int,
    stochastic: bool,
    has_sperm_storage: bool,
    continuous_sampling: bool,
    deme_id: int = 0,
) -> int:
    """Execute one event from a ``HookProgram``, unpacking all fields.

    This is the **primary adapter** between the HookProgram NamedTuple
    and the flat-array interface of ``execute_csr_event_arrays``.
    Lifecycle templates call this function directly.

    Args:
        program: The compiled HookProgram containing all declarative ops.
        event_id: Which event to execute (EVENT_FIRST=0, EVENT_EARLY=1, …).
        individual_count: 3-D array ``[sex, age, genotype]``, mutated in-place.
        sperm_storage: 3-D array ``[age, genotype, gamete_male]`` for
            age-structured models.  Pass a dummy ``(0,0,0)`` array for
            discrete-generation models.
        tick: Current simulation tick (used for condition evaluation).
        stochastic: Whether to use stochastic survival sampling.
        has_sperm_storage: Whether *sperm_storage* contains real data.
        continuous_sampling: Whether to use continuous-Dirichlet sampling.
        deme_id: Deme index for spatial models (0 for panmictic).

    Returns:
        ``RESULT_CONTINUE`` or ``RESULT_STOP``.
    """
    return execute_csr_event_arrays(
        program.n_events,
        program.n_hooks,
        program.hook_offsets,
        program.n_ops_list,
        program.op_offsets,
        program.op_types_data,
        program.gidx_offsets_data,
        program.gidx_data,
        program.age_offsets_data,
        program.age_data,
        program.sex_masks_data,
        program.params_data,
        program.condition_offsets_data,
        program.condition_types_data,
        program.condition_params_data,
        program.deme_selector_types,
        program.deme_selector_offsets,
        program.deme_selector_data,
        event_id,
        individual_count,
        sperm_storage,
        has_sperm_storage,
        tick,
        stochastic,
        continuous_sampling,
        deme_id,
    )


@njit_switch(cache=True)
def execute_csr_event_program(
    program: HookProgram,
    event_id: int,
    individual_count: np.ndarray,
    tick: int,
) -> int:
    """Convenience wrapper with deterministic defaults and no sperm storage.

    Suitable for quick tests or simple discrete-generation setups.
    For production use, prefer ``execute_csr_event_program_with_state``
    which exposes the full state flags.
    """
    dummy_sperm = np.zeros((0, 0, 0), dtype=np.float64)
    return execute_csr_event_program_with_state(
        program,
        event_id,
        individual_count,
        dummy_sperm,
        tick,
        stochastic=False,
        has_sperm_storage=False,
        continuous_sampling=False,
        deme_id=0,
    )


# ===================================================================
# Python fallback: HookExecutor
# ===================================================================
# This class is used ONLY when Numba is disabled.  It provides a
# unified dispatch loop where CSR plans, njit functions, and Python
# wrappers coexist in a single priority-ordered sequence.
#
# When Numba IS enabled, the compiled path handles dispatch —
# ``CompiledEventHooks.from_compiled_hooks`` generates lifecycle
# wrappers that call CSR and njit hooks directly, including unified
# dispatch for mixed types.  The HookExecutor path is never touched
# in that case.
# ===================================================================


class HookExecutor:
    """Python-layer coordinator for hook execution (Numba-disabled only).

    When Numba is disabled, all hook types (CSR plans, njit functions,
    and Python wrappers) must run through a single sequential path.
    This class holds the descriptors sorted by ``priority`` and
    dispatches each one in order.

    For CSR descriptors, it calls ``execute_csr_event_arrays`` with
    the descriptor's ``plan`` unpacked as individual arrays.  For njit
    and py_wrapper descriptors, it calls them directly.

    .. note::
       In Numba-enabled mode, this executor is never constructed.
       ``BasePopulation.should_use_python_dispatch()`` returns False,
       and the compiled lifecycle wrappers handle everything.
    """

    def __init__(
        self,
        registry: HookProgram,
        hooks_by_event: Dict[int, List[CompiledHookDescriptor]],
    ) -> None:
        """Create an executor with a pre-built registry and descriptor map.

        Args:
            registry: The HookProgram for CSR operations (may be empty
                if there are no declarative hooks).
            hooks_by_event: Descriptors grouped and sorted by event_id
                and priority.  Built by ``from_compiled_hooks``.
        """
        self.registry = registry
        self.hooks_by_event = hooks_by_event

    @staticmethod
    def from_compiled_hooks(
        registry: HookProgram,
        compiled_hooks: List[CompiledHookDescriptor],
    ) -> HookExecutor:
        """Group descriptors by event_id and sort by priority.

        Descriptors without a recognised event_id or without any
        execution payload (plan / njit_fn / py_wrapper all None)
        are silently skipped.
        """
        from collections import defaultdict

        hooks_by_event: Dict[int, List[CompiledHookDescriptor]] = defaultdict(list)
        for desc in compiled_hooks:
            event_id = EVENT_ID_MAP.get(desc.event)
            if event_id is not None:
                # Only include descriptors that have something to execute.
                if desc.plan is not None or desc.njit_fn is not None or desc.py_wrapper is not None:
                    hooks_by_event[event_id].append(desc)

        # Sort each event's descriptors by priority (stable — ties keep
        # registration order).
        for event_id in hooks_by_event:
            hooks_by_event[event_id].sort(key=lambda x: x.priority)

        return HookExecutor(registry, dict(hooks_by_event))

    def execute_event(
        self,
        event_id: int,
        population: BasePopulation[Any],
        tick: int,
        deme_id: int = 0,
    ) -> int:
        """Run all hooks for *event_id* in priority order.

        For each descriptor in the pre-sorted list:

        1. **CSR plan** (``desc.plan is not None``):
           Unpacks the plan's arrays and calls ``execute_csr_event_arrays``
           with a single-hook, single-event wrapper.  If it returns
           ``RESULT_STOP``, the event is aborted immediately.

        2. **Njit function** (``desc.njit_fn is not None``):
           Calls ``desc.njit_fn(population.state, population.config, deme_id)``.

        3. **Python wrapper** (``desc.py_wrapper is not None`` and no njit_fn):
           Calls the wrapper with the population object or state/config
           depending on its signature (1 param = population-level,
           3 params = state/config/deme_id).

        Returns:
            ``RESULT_CONTINUE`` or ``RESULT_STOP``.
        """
        if event_id < 0 or event_id >= NUM_EVENTS:
            return RESULT_CONTINUE

        ind_count = population.state.individual_count

        # ---- Resolve runtime state flags ----
        sperm_store = getattr(population.state, "sperm_storage", None)
        has_sperm_storage = sperm_store is not None and sperm_store.size > 0
        if not has_sperm_storage:
            # Discrete-generation or male-only — use a dummy.
            sperm_store = np.zeros((0, 0, 0), dtype=np.float64)
        assert sperm_store is not None
        stochastic = bool(getattr(getattr(population, "_config", None), "stochastic", False))
        continuous_sampling = bool(
            getattr(getattr(population, "_config", None), "continuous_sampling", False)
        )

        from ..numba_utils import NUMBA_ENABLED

        # Descriptors are pre-sorted by priority in from_compiled_hooks.
        # This loop is the ONLY place where CSR, njit, and py_wrapper
        # hooks are interleaved by priority in the Python fallback path.
        for desc in self.hooks_by_event.get(event_id, []):
            # ---- Deme guard (Python path) ----
            if not deme_selector_matches(desc.deme_selector, deme_id):
                continue

            # ---- CSR: declarative Op.* ----
            if desc.plan is not None:
                # Wrap the single plan as a 1-event, 1-hook CSR program.
                result = execute_csr_event_arrays(
                    np.int32(1),                          # n_events
                    np.int32(1),                          # n_hooks
                    np.array([0, 1], dtype=np.int32),     # hook_offsets
                    np.array([desc.plan.n_ops], dtype=np.int32),  # n_ops_list
                    np.array([0, desc.plan.n_ops], dtype=np.int32),  # op_offsets
                    desc.plan.op_types,
                    desc.plan.gidx_offsets,
                    desc.plan.gidx_data,
                    desc.plan.age_offsets,
                    desc.plan.age_data,
                    desc.plan.sex_masks.flatten(),
                    desc.plan.params,
                    desc.plan.condition_offsets,
                    desc.plan.condition_types,
                    desc.plan.condition_params,
                    np.array([0], dtype=np.int32),        # selector type: ANY
                    np.array([0, 0], dtype=np.int32),     # selector offsets
                    np.array([], dtype=np.int32),         # selector data
                    0,                                     # event_id (always 0 in wrapper)
                    ind_count,
                    sperm_store,
                    has_sperm_storage,
                    tick,
                    stochastic,
                    continuous_sampling,
                    deme_id,
                )
                if result == RESULT_STOP:
                    return RESULT_STOP

            # ---- Njit: compiled custom/selector hook ----
            if desc.njit_fn is not None:
                try:
                    result = desc.njit_fn(population.state, population.config, deme_id)
                    if result == RESULT_STOP:
                        return RESULT_STOP
                except Exception as e:
                    raise RuntimeError(f"Error in njit hook '{desc.name}': {e}") from e

            # ---- Python wrapper: pure-Python hook (Numba off) ----
            if desc.py_wrapper is not None and desc.njit_fn is None:
                if NUMBA_ENABLED:
                    # Safety: py_wrapper should never reach here with Numba on.
                    raise RuntimeError(
                        f"Python py_wrapper hook '{desc.name}' is not allowed when Numba is enabled."
                    )
                try:
                    import inspect

                    sig = inspect.signature(desc.py_wrapper)
                    params = list(sig.parameters.values())
                    if len(params) == 1:
                        # Single-parameter → population-level hook (legacy).
                        desc.py_wrapper(population)
                    else:
                        # Multi-parameter → (state, config, deme_id).
                        desc.py_wrapper(population.state, population.config, deme_id)
                except Exception as e:
                    raise RuntimeError(f"Error in py_wrapper hook '{desc.name}': {e}") from e

        return RESULT_CONTINUE

    def get_hooks_for_event(self, event_id: int) -> List[CompiledHookDescriptor]:
        """Return all descriptors registered for *event_id*, sorted by priority."""
        return self.hooks_by_event.get(event_id, [])
